version: '3'

networks:
    inv:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        depends_on:
            - python_app
        networks:
            - inv

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=P@ssw0rd
        networks:
            - inv

    python_app:
        build: ../py_app
        image: py_app:latest
        container_name: python_app
        environment: 
            - APPLICATION_SETTINGS=config.py
        ports:
            - "9000:9000"
        networks:
            - inv

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        ports:
            - "8081:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mariadb
        networks:
            - inv
            